//
//  SimpleDistributedOrderMocks.generated.swift
//  SimpleDistributedOrder
//
//  Generated by Mockingbird v0.20.0.
//  DO NOT EDIT
//

@testable import Mockingbird
@testable import SimpleDistributedOrder
import Foundation
import Swift
import SwiftData
import SwiftUI
import UIKit

private let mkbGenericStaticMockContext = Mockingbird.GenericStaticMockContext()


// MARK: - Mocked ProductItemViewModel
public final class ProductItemViewModelMock: SimpleDistributedOrder.ProductItemViewModel, Mockingbird.Mock {
  typealias MockingbirdSupertype = SimpleDistributedOrder.ProductItemViewModel
  public static let mockingbirdContext = Mockingbird.Context()
  public let mockingbirdContext = Mockingbird.Context(["generator_version": "0.20.0", "module_name": "SimpleDistributedOrder"])

  public enum InitializerProxy {
    public static func initialize(`item`: SimpleDistributedOrder.ProductItem, __file: StaticString = #file, __line: UInt = #line) -> ProductItemViewModelMock {
      let mock: ProductItemViewModelMock = ProductItemViewModelMock(item: `item`)
      mock.mockingbirdContext.sourceLocation = SourceLocation(__file, __line)
      return mock
    }
  }

  // MARK: Mocked iconName
  override public var `iconName`: String {
    get {
      return self.mockingbirdContext.mocking.didInvoke(Mockingbird.SwiftInvocation(selectorName: "iconName.getter", setterSelectorName: "iconName.setter", selectorType: Mockingbird.SelectorType.getter, arguments: [], returnType: Swift.ObjectIdentifier((String).self))) {
        self.mockingbirdContext.recordInvocation($0)
        let mkbImpl = self.mockingbirdContext.stubbing.implementation(for: $0)
        if let mkbImpl = mkbImpl as? () -> String { return mkbImpl() }
        if let mkbImpl = mkbImpl as? () -> Any { return Mockingbird.dynamicCast(mkbImpl()) as String }
        for mkbTargetBox in self.mockingbirdContext.proxy.targets(for: $0) {
          switch mkbTargetBox.target {
          case .super:
            return super.`iconName`
          case .object(let mkbObject):
            guard var mkbObject = mkbObject as? MockingbirdSupertype else { break }
            let mkbValue: String = mkbObject.`iconName`
            self.mockingbirdContext.proxy.updateTarget(&mkbObject, in: mkbTargetBox)
            return mkbValue
          }
        }
        if let mkbValue = self.mockingbirdContext.stubbing.defaultValueProvider.value.provideValue(for: (String).self) { return mkbValue }
        self.mockingbirdContext.stubbing.failTest(for: $0, at: self.mockingbirdContext.sourceLocation)
      }
    }
    set {
      return self.mockingbirdContext.mocking.didInvoke(Mockingbird.SwiftInvocation(selectorName: "iconName.setter", setterSelectorName: "iconName.setter", selectorType: Mockingbird.SelectorType.setter, arguments: [Mockingbird.ArgumentMatcher(newValue)], returnType: Swift.ObjectIdentifier(Void.self))) {
        self.mockingbirdContext.recordInvocation($0)
        let mkbImpl = self.mockingbirdContext.stubbing.implementation(for: $0)
        if let mkbImpl = mkbImpl as? (String) -> Void { return mkbImpl(newValue) }
        if let mkbImpl = mkbImpl as? () -> Void { return mkbImpl() }
        if let mkbImpl = mkbImpl as? (Any?) -> Any { return Mockingbird.dynamicCast(mkbImpl(newValue as Any?)) as Void }
        if let mkbImpl = mkbImpl as? () -> Any { return Mockingbird.dynamicCast(mkbImpl()) as Void }
        for mkbTargetBox in self.mockingbirdContext.proxy.targets(for: $0) {
          switch mkbTargetBox.target {
          case .super:
            return super.`iconName` = newValue
          case .object(let mkbObject):
            guard var mkbObject = mkbObject as? MockingbirdSupertype else { break }
            let mkbValue: Void = mkbObject.`iconName` = newValue
            self.mockingbirdContext.proxy.updateTarget(&mkbObject, in: mkbTargetBox)
            return mkbValue
          }
        }
        if let mkbValue = self.mockingbirdContext.stubbing.defaultValueProvider.value.provideValue(for: (Void).self) { return mkbValue }
        self.mockingbirdContext.stubbing.failTest(for: $0, at: self.mockingbirdContext.sourceLocation)
      }
    }
  }

  public func getIconName() -> Mockingbird.Mockable<Mockingbird.PropertyGetterDeclaration, () -> String, String> {
    return Mockingbird.Mockable<Mockingbird.PropertyGetterDeclaration, () -> String, String>(context: self.mockingbirdContext, invocation: Mockingbird.SwiftInvocation(selectorName: "iconName.getter", setterSelectorName: "iconName.setter", selectorType: Mockingbird.SelectorType.getter, arguments: [], returnType: Swift.ObjectIdentifier((String).self)))
  }

  public func setIconName(_ newValue: @autoclosure () -> String) -> Mockingbird.Mockable<Mockingbird.PropertySetterDeclaration, (String) -> Void, Void> {
    return Mockingbird.Mockable<Mockingbird.PropertySetterDeclaration, (String) -> Void, Void>(context: self.mockingbirdContext, invocation: Mockingbird.SwiftInvocation(selectorName: "iconName.setter", setterSelectorName: "iconName.setter", selectorType: Mockingbird.SelectorType.setter, arguments: [Mockingbird.resolve(newValue)], returnType: Swift.ObjectIdentifier(Void.self)))
  }

  // MARK: Mocked item
  override public var `item`: SimpleDistributedOrder.ProductItem {
    get {
      return self.mockingbirdContext.mocking.didInvoke(Mockingbird.SwiftInvocation(selectorName: "item.getter", setterSelectorName: "item.setter", selectorType: Mockingbird.SelectorType.getter, arguments: [], returnType: Swift.ObjectIdentifier((SimpleDistributedOrder.ProductItem).self))) {
        self.mockingbirdContext.recordInvocation($0)
        let mkbImpl = self.mockingbirdContext.stubbing.implementation(for: $0)
        if let mkbImpl = mkbImpl as? () -> SimpleDistributedOrder.ProductItem { return mkbImpl() }
        if let mkbImpl = mkbImpl as? () -> Any { return Mockingbird.dynamicCast(mkbImpl()) as SimpleDistributedOrder.ProductItem }
        for mkbTargetBox in self.mockingbirdContext.proxy.targets(for: $0) {
          switch mkbTargetBox.target {
          case .super:
            return super.`item`
          case .object(let mkbObject):
            guard var mkbObject = mkbObject as? MockingbirdSupertype else { break }
            let mkbValue: SimpleDistributedOrder.ProductItem = mkbObject.`item`
            self.mockingbirdContext.proxy.updateTarget(&mkbObject, in: mkbTargetBox)
            return mkbValue
          }
        }
        if let mkbValue = self.mockingbirdContext.stubbing.defaultValueProvider.value.provideValue(for: (SimpleDistributedOrder.ProductItem).self) { return mkbValue }
        self.mockingbirdContext.stubbing.failTest(for: $0, at: self.mockingbirdContext.sourceLocation)
      }
    }
    set {
      return self.mockingbirdContext.mocking.didInvoke(Mockingbird.SwiftInvocation(selectorName: "item.setter", setterSelectorName: "item.setter", selectorType: Mockingbird.SelectorType.setter, arguments: [Mockingbird.ArgumentMatcher(newValue)], returnType: Swift.ObjectIdentifier(Void.self))) {
        self.mockingbirdContext.recordInvocation($0)
        let mkbImpl = self.mockingbirdContext.stubbing.implementation(for: $0)
        if let mkbImpl = mkbImpl as? (SimpleDistributedOrder.ProductItem) -> Void { return mkbImpl(newValue) }
        if let mkbImpl = mkbImpl as? () -> Void { return mkbImpl() }
        if let mkbImpl = mkbImpl as? (Any?) -> Any { return Mockingbird.dynamicCast(mkbImpl(newValue as Any?)) as Void }
        if let mkbImpl = mkbImpl as? () -> Any { return Mockingbird.dynamicCast(mkbImpl()) as Void }
        for mkbTargetBox in self.mockingbirdContext.proxy.targets(for: $0) {
          switch mkbTargetBox.target {
          case .super:
            return super.`item` = newValue
          case .object(let mkbObject):
            guard var mkbObject = mkbObject as? MockingbirdSupertype else { break }
            let mkbValue: Void = mkbObject.`item` = newValue
            self.mockingbirdContext.proxy.updateTarget(&mkbObject, in: mkbTargetBox)
            return mkbValue
          }
        }
        if let mkbValue = self.mockingbirdContext.stubbing.defaultValueProvider.value.provideValue(for: (Void).self) { return mkbValue }
        self.mockingbirdContext.stubbing.failTest(for: $0, at: self.mockingbirdContext.sourceLocation)
      }
    }
  }

  public func getItem() -> Mockingbird.Mockable<Mockingbird.PropertyGetterDeclaration, () -> SimpleDistributedOrder.ProductItem, SimpleDistributedOrder.ProductItem> {
    return Mockingbird.Mockable<Mockingbird.PropertyGetterDeclaration, () -> SimpleDistributedOrder.ProductItem, SimpleDistributedOrder.ProductItem>(context: self.mockingbirdContext, invocation: Mockingbird.SwiftInvocation(selectorName: "item.getter", setterSelectorName: "item.setter", selectorType: Mockingbird.SelectorType.getter, arguments: [], returnType: Swift.ObjectIdentifier((SimpleDistributedOrder.ProductItem).self)))
  }

  public func setItem(_ newValue: @autoclosure () -> SimpleDistributedOrder.ProductItem) -> Mockingbird.Mockable<Mockingbird.PropertySetterDeclaration, (SimpleDistributedOrder.ProductItem) -> Void, Void> {
    return Mockingbird.Mockable<Mockingbird.PropertySetterDeclaration, (SimpleDistributedOrder.ProductItem) -> Void, Void>(context: self.mockingbirdContext, invocation: Mockingbird.SwiftInvocation(selectorName: "item.setter", setterSelectorName: "item.setter", selectorType: Mockingbird.SelectorType.setter, arguments: [Mockingbird.resolve(newValue)], returnType: Swift.ObjectIdentifier(Void.self)))
  }

  // MARK: Mocked `getIconName`(`selected`: Bool)
  public override static func `getIconName`(`selected`: Bool) -> String {
    return self.mockingbirdContext.mocking.didInvoke(Mockingbird.SwiftInvocation(selectorName: "`getIconName`(`selected`: Bool) -> String", selectorType: Mockingbird.SelectorType.method, arguments: [Mockingbird.ArgumentMatcher(`selected`)], returnType: Swift.ObjectIdentifier((String).self))) {
      self.mockingbirdContext.recordInvocation($0)
      let mkbImpl = self.mockingbirdContext.stubbing.implementation(for: $0)
      if let mkbImpl = mkbImpl as? (Bool) -> String { return mkbImpl(`selected`) }
      if let mkbImpl = mkbImpl as? () -> String { return mkbImpl() }
      for mkbTargetBox in self.mockingbirdContext.proxy.targets(for: $0) {
        switch mkbTargetBox.target {
        case .super:
          return super.`getIconName`(selected: `selected`)
        case .object(let mkbObject):
          guard var mkbObject = mkbObject as? MockingbirdSupertype.Type else { break }
          let mkbValue: String = mkbObject.`getIconName`(selected: `selected`)
          self.mockingbirdContext.proxy.updateTarget(&mkbObject, in: mkbTargetBox)
          return mkbValue
        }
      }
      if let mkbValue = self.mockingbirdContext.stubbing.defaultValueProvider.value.provideValue(for: (String).self) { return mkbValue }
      self.mockingbirdContext.stubbing.failTest(for: $0, at: self.mockingbirdContext.sourceLocation)
    }
  }

  public static func `getIconName`(`selected`: @autoclosure () -> Bool) -> Mockingbird.Mockable<Mockingbird.FunctionDeclaration, (Bool) -> String, String> {
    return Mockingbird.Mockable<Mockingbird.FunctionDeclaration, (Bool) -> String, String>(context: self.mockingbirdContext, invocation: Mockingbird.SwiftInvocation(selectorName: "`getIconName`(`selected`: Bool) -> String", selectorType: Mockingbird.SelectorType.method, arguments: [Mockingbird.resolve(`selected`)], returnType: Swift.ObjectIdentifier((String).self)))
  }

  // MARK: Mocked `getPriceText`()
  public override func `getPriceText`() -> String {
    return self.mockingbirdContext.mocking.didInvoke(Mockingbird.SwiftInvocation(selectorName: "`getPriceText`() -> String", selectorType: Mockingbird.SelectorType.method, arguments: [], returnType: Swift.ObjectIdentifier((String).self))) {
      self.mockingbirdContext.recordInvocation($0)
      let mkbImpl = self.mockingbirdContext.stubbing.implementation(for: $0)
      if let mkbImpl = mkbImpl as? () -> String { return mkbImpl() }
      for mkbTargetBox in self.mockingbirdContext.proxy.targets(for: $0) {
        switch mkbTargetBox.target {
        case .super:
          return super.`getPriceText`()
        case .object(let mkbObject):
          guard var mkbObject = mkbObject as? MockingbirdSupertype else { break }
          let mkbValue: String = mkbObject.`getPriceText`()
          self.mockingbirdContext.proxy.updateTarget(&mkbObject, in: mkbTargetBox)
          return mkbValue
        }
      }
      if let mkbValue = self.mockingbirdContext.stubbing.defaultValueProvider.value.provideValue(for: (String).self) { return mkbValue }
      self.mockingbirdContext.stubbing.failTest(for: $0, at: self.mockingbirdContext.sourceLocation)
    }
  }

  public func `getPriceText`() -> Mockingbird.Mockable<Mockingbird.FunctionDeclaration, () -> String, String> {
    return Mockingbird.Mockable<Mockingbird.FunctionDeclaration, () -> String, String>(context: self.mockingbirdContext, invocation: Mockingbird.SwiftInvocation(selectorName: "`getPriceText`() -> String", selectorType: Mockingbird.SelectorType.method, arguments: [], returnType: Swift.ObjectIdentifier((String).self)))
  }

  // MARK: Mocked `getWeightText`()
  public override func `getWeightText`() -> String {
    return self.mockingbirdContext.mocking.didInvoke(Mockingbird.SwiftInvocation(selectorName: "`getWeightText`() -> String", selectorType: Mockingbird.SelectorType.method, arguments: [], returnType: Swift.ObjectIdentifier((String).self))) {
      self.mockingbirdContext.recordInvocation($0)
      let mkbImpl = self.mockingbirdContext.stubbing.implementation(for: $0)
      if let mkbImpl = mkbImpl as? () -> String { return mkbImpl() }
      for mkbTargetBox in self.mockingbirdContext.proxy.targets(for: $0) {
        switch mkbTargetBox.target {
        case .super:
          return super.`getWeightText`()
        case .object(let mkbObject):
          guard var mkbObject = mkbObject as? MockingbirdSupertype else { break }
          let mkbValue: String = mkbObject.`getWeightText`()
          self.mockingbirdContext.proxy.updateTarget(&mkbObject, in: mkbTargetBox)
          return mkbValue
        }
      }
      if let mkbValue = self.mockingbirdContext.stubbing.defaultValueProvider.value.provideValue(for: (String).self) { return mkbValue }
      self.mockingbirdContext.stubbing.failTest(for: $0, at: self.mockingbirdContext.sourceLocation)
    }
  }

  public func `getWeightText`() -> Mockingbird.Mockable<Mockingbird.FunctionDeclaration, () -> String, String> {
    return Mockingbird.Mockable<Mockingbird.FunctionDeclaration, () -> String, String>(context: self.mockingbirdContext, invocation: Mockingbird.SwiftInvocation(selectorName: "`getWeightText`() -> String", selectorType: Mockingbird.SelectorType.method, arguments: [], returnType: Swift.ObjectIdentifier((String).self)))
  }

  // MARK: Mocked `updateIconName`()
  public override func `updateIconName`() -> Void {
    return self.mockingbirdContext.mocking.didInvoke(Mockingbird.SwiftInvocation(selectorName: "`updateIconName`() -> Void", selectorType: Mockingbird.SelectorType.method, arguments: [], returnType: Swift.ObjectIdentifier((Void).self))) {
      self.mockingbirdContext.recordInvocation($0)
      let mkbImpl = self.mockingbirdContext.stubbing.implementation(for: $0)
      if let mkbImpl = mkbImpl as? () -> Void { return mkbImpl() }
      for mkbTargetBox in self.mockingbirdContext.proxy.targets(for: $0) {
        switch mkbTargetBox.target {
        case .super:
          return super.`updateIconName`()
        case .object(let mkbObject):
          guard var mkbObject = mkbObject as? MockingbirdSupertype else { break }
          let mkbValue: Void = mkbObject.`updateIconName`()
          self.mockingbirdContext.proxy.updateTarget(&mkbObject, in: mkbTargetBox)
          return mkbValue
        }
      }
      if let mkbValue = self.mockingbirdContext.stubbing.defaultValueProvider.value.provideValue(for: (Void).self) { return mkbValue }
      self.mockingbirdContext.stubbing.failTest(for: $0, at: self.mockingbirdContext.sourceLocation)
    }
  }

  public func `updateIconName`() -> Mockingbird.Mockable<Mockingbird.FunctionDeclaration, () -> Void, Void> {
    return Mockingbird.Mockable<Mockingbird.FunctionDeclaration, () -> Void, Void>(context: self.mockingbirdContext, invocation: Mockingbird.SwiftInvocation(selectorName: "`updateIconName`() -> Void", selectorType: Mockingbird.SelectorType.method, arguments: [], returnType: Swift.ObjectIdentifier((Void).self)))
  }

  // MARK: Mocked `updateSelected`()
  public override func `updateSelected`() -> Void {
    return self.mockingbirdContext.mocking.didInvoke(Mockingbird.SwiftInvocation(selectorName: "`updateSelected`() -> Void", selectorType: Mockingbird.SelectorType.method, arguments: [], returnType: Swift.ObjectIdentifier((Void).self))) {
      self.mockingbirdContext.recordInvocation($0)
      let mkbImpl = self.mockingbirdContext.stubbing.implementation(for: $0)
      if let mkbImpl = mkbImpl as? () -> Void { return mkbImpl() }
      for mkbTargetBox in self.mockingbirdContext.proxy.targets(for: $0) {
        switch mkbTargetBox.target {
        case .super:
          return super.`updateSelected`()
        case .object(let mkbObject):
          guard var mkbObject = mkbObject as? MockingbirdSupertype else { break }
          let mkbValue: Void = mkbObject.`updateSelected`()
          self.mockingbirdContext.proxy.updateTarget(&mkbObject, in: mkbTargetBox)
          return mkbValue
        }
      }
      if let mkbValue = self.mockingbirdContext.stubbing.defaultValueProvider.value.provideValue(for: (Void).self) { return mkbValue }
      self.mockingbirdContext.stubbing.failTest(for: $0, at: self.mockingbirdContext.sourceLocation)
    }
  }

  public func `updateSelected`() -> Mockingbird.Mockable<Mockingbird.FunctionDeclaration, () -> Void, Void> {
    return Mockingbird.Mockable<Mockingbird.FunctionDeclaration, () -> Void, Void>(context: self.mockingbirdContext, invocation: Mockingbird.SwiftInvocation(selectorName: "`updateSelected`() -> Void", selectorType: Mockingbird.SelectorType.method, arguments: [], returnType: Swift.ObjectIdentifier((Void).self)))
  }

  // MARK: Mocked init(`item`: SimpleDistributedOrder.ProductItem)
  public required override init(`item`: SimpleDistributedOrder.ProductItem) {
    super.init(item: `item`)
    self.mockingbirdContext.mocking.didInvoke(Mockingbird.SwiftInvocation(selectorName: "init(`item`: SimpleDistributedOrder.ProductItem)", selectorType: Mockingbird.SelectorType.method, arguments: [Mockingbird.ArgumentMatcher(`item`)], returnType: Swift.ObjectIdentifier((Void).self)))
  }

  public func initialize(`item`: @autoclosure () -> SimpleDistributedOrder.ProductItem) -> Mockingbird.Mockable<Mockingbird.FunctionDeclaration, (SimpleDistributedOrder.ProductItem) -> Void, Void> {
    return Mockingbird.Mockable<Mockingbird.FunctionDeclaration, (SimpleDistributedOrder.ProductItem) -> Void, Void>(context: self.mockingbirdContext, invocation: Mockingbird.SwiftInvocation(selectorName: "init(`item`: SimpleDistributedOrder.ProductItem)", selectorType: Mockingbird.SelectorType.method, arguments: [Mockingbird.resolve(`item`)], returnType: Swift.ObjectIdentifier((Void).self)))
  }
}

/// Returns an abstract mock which should be initialized using `mock(ProductItemViewModel.self).initialize(…)`.
public func mock(_ type: SimpleDistributedOrder.ProductItemViewModel.Type, file: StaticString = #file, line: UInt = #line) -> ProductItemViewModelMock.InitializerProxy.Type {
  return ProductItemViewModelMock.InitializerProxy.self
}

// MARK: - Mocked ProductListViewModel
public final class ProductListViewModelMock: SimpleDistributedOrder.ProductListViewModel, Mockingbird.Mock {
  typealias MockingbirdSupertype = SimpleDistributedOrder.ProductListViewModel
  public static let mockingbirdContext = Mockingbird.Context()
  public let mockingbirdContext = Mockingbird.Context(["generator_version": "0.20.0", "module_name": "SimpleDistributedOrder"])

  public enum InitializerProxy {
    public static func initialize(`dataSource`: SimpleDistributedOrder.ProductSwiftDataServiceProtocol, __file: StaticString = #file, __line: UInt = #line) -> ProductListViewModelMock {
      let mock: ProductListViewModelMock = ProductListViewModelMock(dataSource: `dataSource`)
      mock.mockingbirdContext.sourceLocation = SourceLocation(__file, __line)
      return mock
    }
  }

  // MARK: Mocked packageList
  override public var `packageList`: [SimpleDistributedOrder.ProductsPackage] {
    get {
      return self.mockingbirdContext.mocking.didInvoke(Mockingbird.SwiftInvocation(selectorName: "packageList.getter", setterSelectorName: "packageList.setter", selectorType: Mockingbird.SelectorType.getter, arguments: [], returnType: Swift.ObjectIdentifier(([SimpleDistributedOrder.ProductsPackage]).self))) {
        self.mockingbirdContext.recordInvocation($0)
        let mkbImpl = self.mockingbirdContext.stubbing.implementation(for: $0)
        if let mkbImpl = mkbImpl as? () -> [SimpleDistributedOrder.ProductsPackage] { return mkbImpl() }
        if let mkbImpl = mkbImpl as? () -> Any { return Mockingbird.dynamicCast(mkbImpl()) as [SimpleDistributedOrder.ProductsPackage] }
        for mkbTargetBox in self.mockingbirdContext.proxy.targets(for: $0) {
          switch mkbTargetBox.target {
          case .super:
            return super.`packageList`
          case .object(let mkbObject):
            guard var mkbObject = mkbObject as? MockingbirdSupertype else { break }
            let mkbValue: [SimpleDistributedOrder.ProductsPackage] = mkbObject.`packageList`
            self.mockingbirdContext.proxy.updateTarget(&mkbObject, in: mkbTargetBox)
            return mkbValue
          }
        }
        if let mkbValue = self.mockingbirdContext.stubbing.defaultValueProvider.value.provideValue(for: ([SimpleDistributedOrder.ProductsPackage]).self) { return mkbValue }
        self.mockingbirdContext.stubbing.failTest(for: $0, at: self.mockingbirdContext.sourceLocation)
      }
    }
    set {
      return self.mockingbirdContext.mocking.didInvoke(Mockingbird.SwiftInvocation(selectorName: "packageList.setter", setterSelectorName: "packageList.setter", selectorType: Mockingbird.SelectorType.setter, arguments: [Mockingbird.ArgumentMatcher(newValue)], returnType: Swift.ObjectIdentifier(Void.self))) {
        self.mockingbirdContext.recordInvocation($0)
        let mkbImpl = self.mockingbirdContext.stubbing.implementation(for: $0)
        if let mkbImpl = mkbImpl as? ([SimpleDistributedOrder.ProductsPackage]) -> Void { return mkbImpl(newValue) }
        if let mkbImpl = mkbImpl as? () -> Void { return mkbImpl() }
        if let mkbImpl = mkbImpl as? (Any?) -> Any { return Mockingbird.dynamicCast(mkbImpl(newValue as Any?)) as Void }
        if let mkbImpl = mkbImpl as? () -> Any { return Mockingbird.dynamicCast(mkbImpl()) as Void }
        for mkbTargetBox in self.mockingbirdContext.proxy.targets(for: $0) {
          switch mkbTargetBox.target {
          case .super:
            return super.`packageList` = newValue
          case .object(let mkbObject):
            guard var mkbObject = mkbObject as? MockingbirdSupertype else { break }
            let mkbValue: Void = mkbObject.`packageList` = newValue
            self.mockingbirdContext.proxy.updateTarget(&mkbObject, in: mkbTargetBox)
            return mkbValue
          }
        }
        if let mkbValue = self.mockingbirdContext.stubbing.defaultValueProvider.value.provideValue(for: (Void).self) { return mkbValue }
        self.mockingbirdContext.stubbing.failTest(for: $0, at: self.mockingbirdContext.sourceLocation)
      }
    }
  }

  public func getPackageList() -> Mockingbird.Mockable<Mockingbird.PropertyGetterDeclaration, () -> [SimpleDistributedOrder.ProductsPackage], [SimpleDistributedOrder.ProductsPackage]> {
    return Mockingbird.Mockable<Mockingbird.PropertyGetterDeclaration, () -> [SimpleDistributedOrder.ProductsPackage], [SimpleDistributedOrder.ProductsPackage]>(context: self.mockingbirdContext, invocation: Mockingbird.SwiftInvocation(selectorName: "packageList.getter", setterSelectorName: "packageList.setter", selectorType: Mockingbird.SelectorType.getter, arguments: [], returnType: Swift.ObjectIdentifier(([SimpleDistributedOrder.ProductsPackage]).self)))
  }

  public func setPackageList(_ newValue: @autoclosure () -> [SimpleDistributedOrder.ProductsPackage]) -> Mockingbird.Mockable<Mockingbird.PropertySetterDeclaration, ([SimpleDistributedOrder.ProductsPackage]) -> Void, Void> {
    return Mockingbird.Mockable<Mockingbird.PropertySetterDeclaration, ([SimpleDistributedOrder.ProductsPackage]) -> Void, Void>(context: self.mockingbirdContext, invocation: Mockingbird.SwiftInvocation(selectorName: "packageList.setter", setterSelectorName: "packageList.setter", selectorType: Mockingbird.SelectorType.setter, arguments: [Mockingbird.resolve(newValue)], returnType: Swift.ObjectIdentifier(Void.self)))
  }

  // MARK: Mocked productList
  override public var `productList`: [SimpleDistributedOrder.ProductItem] {
    get {
      return self.mockingbirdContext.mocking.didInvoke(Mockingbird.SwiftInvocation(selectorName: "productList.getter", setterSelectorName: "productList.setter", selectorType: Mockingbird.SelectorType.getter, arguments: [], returnType: Swift.ObjectIdentifier(([SimpleDistributedOrder.ProductItem]).self))) {
        self.mockingbirdContext.recordInvocation($0)
        let mkbImpl = self.mockingbirdContext.stubbing.implementation(for: $0)
        if let mkbImpl = mkbImpl as? () -> [SimpleDistributedOrder.ProductItem] { return mkbImpl() }
        if let mkbImpl = mkbImpl as? () -> Any { return Mockingbird.dynamicCast(mkbImpl()) as [SimpleDistributedOrder.ProductItem] }
        for mkbTargetBox in self.mockingbirdContext.proxy.targets(for: $0) {
          switch mkbTargetBox.target {
          case .super:
            return super.`productList`
          case .object(let mkbObject):
            guard var mkbObject = mkbObject as? MockingbirdSupertype else { break }
            let mkbValue: [SimpleDistributedOrder.ProductItem] = mkbObject.`productList`
            self.mockingbirdContext.proxy.updateTarget(&mkbObject, in: mkbTargetBox)
            return mkbValue
          }
        }
        if let mkbValue = self.mockingbirdContext.stubbing.defaultValueProvider.value.provideValue(for: ([SimpleDistributedOrder.ProductItem]).self) { return mkbValue }
        self.mockingbirdContext.stubbing.failTest(for: $0, at: self.mockingbirdContext.sourceLocation)
      }
    }
    set {
      return self.mockingbirdContext.mocking.didInvoke(Mockingbird.SwiftInvocation(selectorName: "productList.setter", setterSelectorName: "productList.setter", selectorType: Mockingbird.SelectorType.setter, arguments: [Mockingbird.ArgumentMatcher(newValue)], returnType: Swift.ObjectIdentifier(Void.self))) {
        self.mockingbirdContext.recordInvocation($0)
        let mkbImpl = self.mockingbirdContext.stubbing.implementation(for: $0)
        if let mkbImpl = mkbImpl as? ([SimpleDistributedOrder.ProductItem]) -> Void { return mkbImpl(newValue) }
        if let mkbImpl = mkbImpl as? () -> Void { return mkbImpl() }
        if let mkbImpl = mkbImpl as? (Any?) -> Any { return Mockingbird.dynamicCast(mkbImpl(newValue as Any?)) as Void }
        if let mkbImpl = mkbImpl as? () -> Any { return Mockingbird.dynamicCast(mkbImpl()) as Void }
        for mkbTargetBox in self.mockingbirdContext.proxy.targets(for: $0) {
          switch mkbTargetBox.target {
          case .super:
            return super.`productList` = newValue
          case .object(let mkbObject):
            guard var mkbObject = mkbObject as? MockingbirdSupertype else { break }
            let mkbValue: Void = mkbObject.`productList` = newValue
            self.mockingbirdContext.proxy.updateTarget(&mkbObject, in: mkbTargetBox)
            return mkbValue
          }
        }
        if let mkbValue = self.mockingbirdContext.stubbing.defaultValueProvider.value.provideValue(for: (Void).self) { return mkbValue }
        self.mockingbirdContext.stubbing.failTest(for: $0, at: self.mockingbirdContext.sourceLocation)
      }
    }
  }

  public func getProductList() -> Mockingbird.Mockable<Mockingbird.PropertyGetterDeclaration, () -> [SimpleDistributedOrder.ProductItem], [SimpleDistributedOrder.ProductItem]> {
    return Mockingbird.Mockable<Mockingbird.PropertyGetterDeclaration, () -> [SimpleDistributedOrder.ProductItem], [SimpleDistributedOrder.ProductItem]>(context: self.mockingbirdContext, invocation: Mockingbird.SwiftInvocation(selectorName: "productList.getter", setterSelectorName: "productList.setter", selectorType: Mockingbird.SelectorType.getter, arguments: [], returnType: Swift.ObjectIdentifier(([SimpleDistributedOrder.ProductItem]).self)))
  }

  public func setProductList(_ newValue: @autoclosure () -> [SimpleDistributedOrder.ProductItem]) -> Mockingbird.Mockable<Mockingbird.PropertySetterDeclaration, ([SimpleDistributedOrder.ProductItem]) -> Void, Void> {
    return Mockingbird.Mockable<Mockingbird.PropertySetterDeclaration, ([SimpleDistributedOrder.ProductItem]) -> Void, Void>(context: self.mockingbirdContext, invocation: Mockingbird.SwiftInvocation(selectorName: "productList.setter", setterSelectorName: "productList.setter", selectorType: Mockingbird.SelectorType.setter, arguments: [Mockingbird.resolve(newValue)], returnType: Swift.ObjectIdentifier(Void.self)))
  }

  // MARK: Mocked selectedProductList
  override public var `selectedProductList`: [SimpleDistributedOrder.ProductItem] {
    get {
      return self.mockingbirdContext.mocking.didInvoke(Mockingbird.SwiftInvocation(selectorName: "selectedProductList.getter", setterSelectorName: "selectedProductList.setter", selectorType: Mockingbird.SelectorType.getter, arguments: [], returnType: Swift.ObjectIdentifier(([SimpleDistributedOrder.ProductItem]).self))) {
        self.mockingbirdContext.recordInvocation($0)
        let mkbImpl = self.mockingbirdContext.stubbing.implementation(for: $0)
        if let mkbImpl = mkbImpl as? () -> [SimpleDistributedOrder.ProductItem] { return mkbImpl() }
        if let mkbImpl = mkbImpl as? () -> Any { return Mockingbird.dynamicCast(mkbImpl()) as [SimpleDistributedOrder.ProductItem] }
        for mkbTargetBox in self.mockingbirdContext.proxy.targets(for: $0) {
          switch mkbTargetBox.target {
          case .super:
            return super.`selectedProductList`
          case .object(let mkbObject):
            guard var mkbObject = mkbObject as? MockingbirdSupertype else { break }
            let mkbValue: [SimpleDistributedOrder.ProductItem] = mkbObject.`selectedProductList`
            self.mockingbirdContext.proxy.updateTarget(&mkbObject, in: mkbTargetBox)
            return mkbValue
          }
        }
        if let mkbValue = self.mockingbirdContext.stubbing.defaultValueProvider.value.provideValue(for: ([SimpleDistributedOrder.ProductItem]).self) { return mkbValue }
        self.mockingbirdContext.stubbing.failTest(for: $0, at: self.mockingbirdContext.sourceLocation)
      }
    }
    set {
      return self.mockingbirdContext.mocking.didInvoke(Mockingbird.SwiftInvocation(selectorName: "selectedProductList.setter", setterSelectorName: "selectedProductList.setter", selectorType: Mockingbird.SelectorType.setter, arguments: [Mockingbird.ArgumentMatcher(newValue)], returnType: Swift.ObjectIdentifier(Void.self))) {
        self.mockingbirdContext.recordInvocation($0)
        let mkbImpl = self.mockingbirdContext.stubbing.implementation(for: $0)
        if let mkbImpl = mkbImpl as? ([SimpleDistributedOrder.ProductItem]) -> Void { return mkbImpl(newValue) }
        if let mkbImpl = mkbImpl as? () -> Void { return mkbImpl() }
        if let mkbImpl = mkbImpl as? (Any?) -> Any { return Mockingbird.dynamicCast(mkbImpl(newValue as Any?)) as Void }
        if let mkbImpl = mkbImpl as? () -> Any { return Mockingbird.dynamicCast(mkbImpl()) as Void }
        for mkbTargetBox in self.mockingbirdContext.proxy.targets(for: $0) {
          switch mkbTargetBox.target {
          case .super:
            return super.`selectedProductList` = newValue
          case .object(let mkbObject):
            guard var mkbObject = mkbObject as? MockingbirdSupertype else { break }
            let mkbValue: Void = mkbObject.`selectedProductList` = newValue
            self.mockingbirdContext.proxy.updateTarget(&mkbObject, in: mkbTargetBox)
            return mkbValue
          }
        }
        if let mkbValue = self.mockingbirdContext.stubbing.defaultValueProvider.value.provideValue(for: (Void).self) { return mkbValue }
        self.mockingbirdContext.stubbing.failTest(for: $0, at: self.mockingbirdContext.sourceLocation)
      }
    }
  }

  public func getSelectedProductList() -> Mockingbird.Mockable<Mockingbird.PropertyGetterDeclaration, () -> [SimpleDistributedOrder.ProductItem], [SimpleDistributedOrder.ProductItem]> {
    return Mockingbird.Mockable<Mockingbird.PropertyGetterDeclaration, () -> [SimpleDistributedOrder.ProductItem], [SimpleDistributedOrder.ProductItem]>(context: self.mockingbirdContext, invocation: Mockingbird.SwiftInvocation(selectorName: "selectedProductList.getter", setterSelectorName: "selectedProductList.setter", selectorType: Mockingbird.SelectorType.getter, arguments: [], returnType: Swift.ObjectIdentifier(([SimpleDistributedOrder.ProductItem]).self)))
  }

  public func setSelectedProductList(_ newValue: @autoclosure () -> [SimpleDistributedOrder.ProductItem]) -> Mockingbird.Mockable<Mockingbird.PropertySetterDeclaration, ([SimpleDistributedOrder.ProductItem]) -> Void, Void> {
    return Mockingbird.Mockable<Mockingbird.PropertySetterDeclaration, ([SimpleDistributedOrder.ProductItem]) -> Void, Void>(context: self.mockingbirdContext, invocation: Mockingbird.SwiftInvocation(selectorName: "selectedProductList.setter", setterSelectorName: "selectedProductList.setter", selectorType: Mockingbird.SelectorType.setter, arguments: [Mockingbird.resolve(newValue)], returnType: Swift.ObjectIdentifier(Void.self)))
  }

  // MARK: Mocked `totalPrice`()
  public override func `totalPrice`() -> Double {
    return self.mockingbirdContext.mocking.didInvoke(Mockingbird.SwiftInvocation(selectorName: "`totalPrice`() -> Double", selectorType: Mockingbird.SelectorType.method, arguments: [], returnType: Swift.ObjectIdentifier((Double).self))) {
      self.mockingbirdContext.recordInvocation($0)
      let mkbImpl = self.mockingbirdContext.stubbing.implementation(for: $0)
      if let mkbImpl = mkbImpl as? () -> Double { return mkbImpl() }
      for mkbTargetBox in self.mockingbirdContext.proxy.targets(for: $0) {
        switch mkbTargetBox.target {
        case .super:
          return super.`totalPrice`()
        case .object(let mkbObject):
          guard var mkbObject = mkbObject as? MockingbirdSupertype else { break }
          let mkbValue: Double = mkbObject.`totalPrice`()
          self.mockingbirdContext.proxy.updateTarget(&mkbObject, in: mkbTargetBox)
          return mkbValue
        }
      }
      if let mkbValue = self.mockingbirdContext.stubbing.defaultValueProvider.value.provideValue(for: (Double).self) { return mkbValue }
      self.mockingbirdContext.stubbing.failTest(for: $0, at: self.mockingbirdContext.sourceLocation)
    }
  }

  public func `totalPrice`() -> Mockingbird.Mockable<Mockingbird.FunctionDeclaration, () -> Double, Double> {
    return Mockingbird.Mockable<Mockingbird.FunctionDeclaration, () -> Double, Double>(context: self.mockingbirdContext, invocation: Mockingbird.SwiftInvocation(selectorName: "`totalPrice`() -> Double", selectorType: Mockingbird.SelectorType.method, arguments: [], returnType: Swift.ObjectIdentifier((Double).self)))
  }

  // MARK: Mocked `packagePrice`(`package`: SimpleDistributedOrder.ProductsPackage)
  public override func `packagePrice`(`package`: SimpleDistributedOrder.ProductsPackage) -> Double {
    return self.mockingbirdContext.mocking.didInvoke(Mockingbird.SwiftInvocation(selectorName: "`packagePrice`(`package`: SimpleDistributedOrder.ProductsPackage) -> Double", selectorType: Mockingbird.SelectorType.method, arguments: [Mockingbird.ArgumentMatcher(`package`)], returnType: Swift.ObjectIdentifier((Double).self))) {
      self.mockingbirdContext.recordInvocation($0)
      let mkbImpl = self.mockingbirdContext.stubbing.implementation(for: $0)
      if let mkbImpl = mkbImpl as? (SimpleDistributedOrder.ProductsPackage) -> Double { return mkbImpl(`package`) }
      if let mkbImpl = mkbImpl as? () -> Double { return mkbImpl() }
      for mkbTargetBox in self.mockingbirdContext.proxy.targets(for: $0) {
        switch mkbTargetBox.target {
        case .super:
          return super.`packagePrice`(package: `package`)
        case .object(let mkbObject):
          guard var mkbObject = mkbObject as? MockingbirdSupertype else { break }
          let mkbValue: Double = mkbObject.`packagePrice`(package: `package`)
          self.mockingbirdContext.proxy.updateTarget(&mkbObject, in: mkbTargetBox)
          return mkbValue
        }
      }
      if let mkbValue = self.mockingbirdContext.stubbing.defaultValueProvider.value.provideValue(for: (Double).self) { return mkbValue }
      self.mockingbirdContext.stubbing.failTest(for: $0, at: self.mockingbirdContext.sourceLocation)
    }
  }

  public func `packagePrice`(`package`: @autoclosure () -> SimpleDistributedOrder.ProductsPackage) -> Mockingbird.Mockable<Mockingbird.FunctionDeclaration, (SimpleDistributedOrder.ProductsPackage) -> Double, Double> {
    return Mockingbird.Mockable<Mockingbird.FunctionDeclaration, (SimpleDistributedOrder.ProductsPackage) -> Double, Double>(context: self.mockingbirdContext, invocation: Mockingbird.SwiftInvocation(selectorName: "`packagePrice`(`package`: SimpleDistributedOrder.ProductsPackage) -> Double", selectorType: Mockingbird.SelectorType.method, arguments: [Mockingbird.resolve(`package`)], returnType: Swift.ObjectIdentifier((Double).self)))
  }

  // MARK: Mocked `totalWeight`()
  public override func `totalWeight`() -> Int {
    return self.mockingbirdContext.mocking.didInvoke(Mockingbird.SwiftInvocation(selectorName: "`totalWeight`() -> Int", selectorType: Mockingbird.SelectorType.method, arguments: [], returnType: Swift.ObjectIdentifier((Int).self))) {
      self.mockingbirdContext.recordInvocation($0)
      let mkbImpl = self.mockingbirdContext.stubbing.implementation(for: $0)
      if let mkbImpl = mkbImpl as? () -> Int { return mkbImpl() }
      for mkbTargetBox in self.mockingbirdContext.proxy.targets(for: $0) {
        switch mkbTargetBox.target {
        case .super:
          return super.`totalWeight`()
        case .object(let mkbObject):
          guard var mkbObject = mkbObject as? MockingbirdSupertype else { break }
          let mkbValue: Int = mkbObject.`totalWeight`()
          self.mockingbirdContext.proxy.updateTarget(&mkbObject, in: mkbTargetBox)
          return mkbValue
        }
      }
      if let mkbValue = self.mockingbirdContext.stubbing.defaultValueProvider.value.provideValue(for: (Int).self) { return mkbValue }
      self.mockingbirdContext.stubbing.failTest(for: $0, at: self.mockingbirdContext.sourceLocation)
    }
  }

  public func `totalWeight`() -> Mockingbird.Mockable<Mockingbird.FunctionDeclaration, () -> Int, Int> {
    return Mockingbird.Mockable<Mockingbird.FunctionDeclaration, () -> Int, Int>(context: self.mockingbirdContext, invocation: Mockingbird.SwiftInvocation(selectorName: "`totalWeight`() -> Int", selectorType: Mockingbird.SelectorType.method, arguments: [], returnType: Swift.ObjectIdentifier((Int).self)))
  }

  // MARK: Mocked `packageWeight`(`package`: SimpleDistributedOrder.ProductsPackage)
  public override func `packageWeight`(`package`: SimpleDistributedOrder.ProductsPackage) -> Int {
    return self.mockingbirdContext.mocking.didInvoke(Mockingbird.SwiftInvocation(selectorName: "`packageWeight`(`package`: SimpleDistributedOrder.ProductsPackage) -> Int", selectorType: Mockingbird.SelectorType.method, arguments: [Mockingbird.ArgumentMatcher(`package`)], returnType: Swift.ObjectIdentifier((Int).self))) {
      self.mockingbirdContext.recordInvocation($0)
      let mkbImpl = self.mockingbirdContext.stubbing.implementation(for: $0)
      if let mkbImpl = mkbImpl as? (SimpleDistributedOrder.ProductsPackage) -> Int { return mkbImpl(`package`) }
      if let mkbImpl = mkbImpl as? () -> Int { return mkbImpl() }
      for mkbTargetBox in self.mockingbirdContext.proxy.targets(for: $0) {
        switch mkbTargetBox.target {
        case .super:
          return super.`packageWeight`(package: `package`)
        case .object(let mkbObject):
          guard var mkbObject = mkbObject as? MockingbirdSupertype else { break }
          let mkbValue: Int = mkbObject.`packageWeight`(package: `package`)
          self.mockingbirdContext.proxy.updateTarget(&mkbObject, in: mkbTargetBox)
          return mkbValue
        }
      }
      if let mkbValue = self.mockingbirdContext.stubbing.defaultValueProvider.value.provideValue(for: (Int).self) { return mkbValue }
      self.mockingbirdContext.stubbing.failTest(for: $0, at: self.mockingbirdContext.sourceLocation)
    }
  }

  public func `packageWeight`(`package`: @autoclosure () -> SimpleDistributedOrder.ProductsPackage) -> Mockingbird.Mockable<Mockingbird.FunctionDeclaration, (SimpleDistributedOrder.ProductsPackage) -> Int, Int> {
    return Mockingbird.Mockable<Mockingbird.FunctionDeclaration, (SimpleDistributedOrder.ProductsPackage) -> Int, Int>(context: self.mockingbirdContext, invocation: Mockingbird.SwiftInvocation(selectorName: "`packageWeight`(`package`: SimpleDistributedOrder.ProductsPackage) -> Int", selectorType: Mockingbird.SelectorType.method, arguments: [Mockingbird.resolve(`package`)], returnType: Swift.ObjectIdentifier((Int).self)))
  }

  // MARK: Mocked `updatePackages`()
  public override func `updatePackages`() -> Void {
    return self.mockingbirdContext.mocking.didInvoke(Mockingbird.SwiftInvocation(selectorName: "`updatePackages`() -> Void", selectorType: Mockingbird.SelectorType.method, arguments: [], returnType: Swift.ObjectIdentifier((Void).self))) {
      self.mockingbirdContext.recordInvocation($0)
      let mkbImpl = self.mockingbirdContext.stubbing.implementation(for: $0)
      if let mkbImpl = mkbImpl as? () -> Void { return mkbImpl() }
      for mkbTargetBox in self.mockingbirdContext.proxy.targets(for: $0) {
        switch mkbTargetBox.target {
        case .super:
          return super.`updatePackages`()
        case .object(let mkbObject):
          guard var mkbObject = mkbObject as? MockingbirdSupertype else { break }
          let mkbValue: Void = mkbObject.`updatePackages`()
          self.mockingbirdContext.proxy.updateTarget(&mkbObject, in: mkbTargetBox)
          return mkbValue
        }
      }
      if let mkbValue = self.mockingbirdContext.stubbing.defaultValueProvider.value.provideValue(for: (Void).self) { return mkbValue }
      self.mockingbirdContext.stubbing.failTest(for: $0, at: self.mockingbirdContext.sourceLocation)
    }
  }

  public func `updatePackages`() -> Mockingbird.Mockable<Mockingbird.FunctionDeclaration, () -> Void, Void> {
    return Mockingbird.Mockable<Mockingbird.FunctionDeclaration, () -> Void, Void>(context: self.mockingbirdContext, invocation: Mockingbird.SwiftInvocation(selectorName: "`updatePackages`() -> Void", selectorType: Mockingbird.SelectorType.method, arguments: [], returnType: Swift.ObjectIdentifier((Void).self)))
  }

  // MARK: Mocked `updateSelected`()
  public override func `updateSelected`() -> Void {
    return self.mockingbirdContext.mocking.didInvoke(Mockingbird.SwiftInvocation(selectorName: "`updateSelected`() -> Void", selectorType: Mockingbird.SelectorType.method, arguments: [], returnType: Swift.ObjectIdentifier((Void).self))) {
      self.mockingbirdContext.recordInvocation($0)
      let mkbImpl = self.mockingbirdContext.stubbing.implementation(for: $0)
      if let mkbImpl = mkbImpl as? () -> Void { return mkbImpl() }
      for mkbTargetBox in self.mockingbirdContext.proxy.targets(for: $0) {
        switch mkbTargetBox.target {
        case .super:
          return super.`updateSelected`()
        case .object(let mkbObject):
          guard var mkbObject = mkbObject as? MockingbirdSupertype else { break }
          let mkbValue: Void = mkbObject.`updateSelected`()
          self.mockingbirdContext.proxy.updateTarget(&mkbObject, in: mkbTargetBox)
          return mkbValue
        }
      }
      if let mkbValue = self.mockingbirdContext.stubbing.defaultValueProvider.value.provideValue(for: (Void).self) { return mkbValue }
      self.mockingbirdContext.stubbing.failTest(for: $0, at: self.mockingbirdContext.sourceLocation)
    }
  }

  public func `updateSelected`() -> Mockingbird.Mockable<Mockingbird.FunctionDeclaration, () -> Void, Void> {
    return Mockingbird.Mockable<Mockingbird.FunctionDeclaration, () -> Void, Void>(context: self.mockingbirdContext, invocation: Mockingbird.SwiftInvocation(selectorName: "`updateSelected`() -> Void", selectorType: Mockingbird.SelectorType.method, arguments: [], returnType: Swift.ObjectIdentifier((Void).self)))
  }

  // MARK: Mocked init(`dataSource`: SimpleDistributedOrder.ProductSwiftDataServiceProtocol)
  public required override init(`dataSource`: SimpleDistributedOrder.ProductSwiftDataServiceProtocol) {
    super.init(dataSource: `dataSource`)
    self.mockingbirdContext.mocking.didInvoke(Mockingbird.SwiftInvocation(selectorName: "init(`dataSource`: SimpleDistributedOrder.ProductSwiftDataServiceProtocol)", selectorType: Mockingbird.SelectorType.method, arguments: [Mockingbird.ArgumentMatcher(`dataSource`)], returnType: Swift.ObjectIdentifier((Void).self)))
  }

  public func initialize(`dataSource`: @autoclosure () -> SimpleDistributedOrder.ProductSwiftDataServiceProtocol) -> Mockingbird.Mockable<Mockingbird.FunctionDeclaration, (SimpleDistributedOrder.ProductSwiftDataServiceProtocol) -> Void, Void> {
    return Mockingbird.Mockable<Mockingbird.FunctionDeclaration, (SimpleDistributedOrder.ProductSwiftDataServiceProtocol) -> Void, Void>(context: self.mockingbirdContext, invocation: Mockingbird.SwiftInvocation(selectorName: "init(`dataSource`: SimpleDistributedOrder.ProductSwiftDataServiceProtocol)", selectorType: Mockingbird.SelectorType.method, arguments: [Mockingbird.resolve(`dataSource`)], returnType: Swift.ObjectIdentifier((Void).self)))
  }

  // MARK: Mocked `updatePackageInfo`(`name`: String, `package`: inout SimpleDistributedOrder.ProductsPackage)
  public override func `updatePackageInfo`(`name`: String, `package`: inout SimpleDistributedOrder.ProductsPackage) -> Void {
    return self.mockingbirdContext.mocking.didInvoke(Mockingbird.SwiftInvocation(selectorName: "`updatePackageInfo`(`name`: String, `package`: inout SimpleDistributedOrder.ProductsPackage) -> Void", selectorType: Mockingbird.SelectorType.method, arguments: [Mockingbird.ArgumentMatcher(`name`), Mockingbird.ArgumentMatcher(`package`)], returnType: Swift.ObjectIdentifier((Void).self))) {
      self.mockingbirdContext.recordInvocation($0)
      let mkbImpl = self.mockingbirdContext.stubbing.implementation(for: $0)
      if let mkbImpl = mkbImpl as? (String, inout SimpleDistributedOrder.ProductsPackage) -> Void { return mkbImpl(`name`, &`package`) }
      if let mkbImpl = mkbImpl as? () -> Void { return mkbImpl() }
      for mkbTargetBox in self.mockingbirdContext.proxy.targets(for: $0) {
        switch mkbTargetBox.target {
        case .super:
          return super.`updatePackageInfo`(name: `name`, package: &`package`)
        case .object(let mkbObject):
          guard var mkbObject = mkbObject as? MockingbirdSupertype else { break }
          let mkbValue: Void = mkbObject.`updatePackageInfo`(name: `name`, package: &`package`)
          self.mockingbirdContext.proxy.updateTarget(&mkbObject, in: mkbTargetBox)
          return mkbValue
        }
      }
      if let mkbValue = self.mockingbirdContext.stubbing.defaultValueProvider.value.provideValue(for: (Void).self) { return mkbValue }
      self.mockingbirdContext.stubbing.failTest(for: $0, at: self.mockingbirdContext.sourceLocation)
    }
  }

  public func `updatePackageInfo`(`name`: @autoclosure () -> String, `package`: @autoclosure () -> SimpleDistributedOrder.ProductsPackage) -> Mockingbird.Mockable<Mockingbird.FunctionDeclaration, (String, inout SimpleDistributedOrder.ProductsPackage) -> Void, Void> {
    return Mockingbird.Mockable<Mockingbird.FunctionDeclaration, (String, inout SimpleDistributedOrder.ProductsPackage) -> Void, Void>(context: self.mockingbirdContext, invocation: Mockingbird.SwiftInvocation(selectorName: "`updatePackageInfo`(`name`: String, `package`: inout SimpleDistributedOrder.ProductsPackage) -> Void", selectorType: Mockingbird.SelectorType.method, arguments: [Mockingbird.resolve(`name`), Mockingbird.resolve(`package`)], returnType: Swift.ObjectIdentifier((Void).self)))
  }

  // MARK: Mocked `generatePackages`()
  public override func `generatePackages`() -> [SimpleDistributedOrder.ProductsPackage] {
    return self.mockingbirdContext.mocking.didInvoke(Mockingbird.SwiftInvocation(selectorName: "`generatePackages`() -> [SimpleDistributedOrder.ProductsPackage]", selectorType: Mockingbird.SelectorType.method, arguments: [], returnType: Swift.ObjectIdentifier(([SimpleDistributedOrder.ProductsPackage]).self))) {
      self.mockingbirdContext.recordInvocation($0)
      let mkbImpl = self.mockingbirdContext.stubbing.implementation(for: $0)
      if let mkbImpl = mkbImpl as? () -> [SimpleDistributedOrder.ProductsPackage] { return mkbImpl() }
      for mkbTargetBox in self.mockingbirdContext.proxy.targets(for: $0) {
        switch mkbTargetBox.target {
        case .super:
          return super.`generatePackages`()
        case .object(let mkbObject):
          guard var mkbObject = mkbObject as? MockingbirdSupertype else { break }
          let mkbValue: [SimpleDistributedOrder.ProductsPackage] = mkbObject.`generatePackages`()
          self.mockingbirdContext.proxy.updateTarget(&mkbObject, in: mkbTargetBox)
          return mkbValue
        }
      }
      if let mkbValue = self.mockingbirdContext.stubbing.defaultValueProvider.value.provideValue(for: ([SimpleDistributedOrder.ProductsPackage]).self) { return mkbValue }
      self.mockingbirdContext.stubbing.failTest(for: $0, at: self.mockingbirdContext.sourceLocation)
    }
  }

  public func `generatePackages`() -> Mockingbird.Mockable<Mockingbird.FunctionDeclaration, () -> [SimpleDistributedOrder.ProductsPackage], [SimpleDistributedOrder.ProductsPackage]> {
    return Mockingbird.Mockable<Mockingbird.FunctionDeclaration, () -> [SimpleDistributedOrder.ProductsPackage], [SimpleDistributedOrder.ProductsPackage]>(context: self.mockingbirdContext, invocation: Mockingbird.SwiftInvocation(selectorName: "`generatePackages`() -> [SimpleDistributedOrder.ProductsPackage]", selectorType: Mockingbird.SelectorType.method, arguments: [], returnType: Swift.ObjectIdentifier(([SimpleDistributedOrder.ProductsPackage]).self)))
  }
}

/// Returns an abstract mock which should be initialized using `mock(ProductListViewModel.self).initialize(…)`.
public func mock(_ type: SimpleDistributedOrder.ProductListViewModel.Type, file: StaticString = #file, line: UInt = #line) -> ProductListViewModelMock.InitializerProxy.Type {
  return ProductListViewModelMock.InitializerProxy.self
}

// MARK: - Mocked ProductPackageViewModel
public final class ProductPackageViewModelMock: SimpleDistributedOrder.ProductPackageViewModel, Mockingbird.Mock {
  typealias MockingbirdSupertype = SimpleDistributedOrder.ProductPackageViewModel
  public static let mockingbirdContext = Mockingbird.Context()
  public let mockingbirdContext = Mockingbird.Context(["generator_version": "0.20.0", "module_name": "SimpleDistributedOrder"])

  public enum InitializerProxy {
    public static func initialize(`package`: SimpleDistributedOrder.ProductsPackage, __file: StaticString = #file, __line: UInt = #line) -> ProductPackageViewModelMock {
      let mock: ProductPackageViewModelMock = ProductPackageViewModelMock(package: `package`)
      mock.mockingbirdContext.sourceLocation = SourceLocation(__file, __line)
      return mock
    }
  }

  // MARK: Mocked package
  override public var `package`: SimpleDistributedOrder.ProductsPackage {
    get {
      return self.mockingbirdContext.mocking.didInvoke(Mockingbird.SwiftInvocation(selectorName: "package.getter", setterSelectorName: "package.setter", selectorType: Mockingbird.SelectorType.getter, arguments: [], returnType: Swift.ObjectIdentifier((SimpleDistributedOrder.ProductsPackage).self))) {
        self.mockingbirdContext.recordInvocation($0)
        let mkbImpl = self.mockingbirdContext.stubbing.implementation(for: $0)
        if let mkbImpl = mkbImpl as? () -> SimpleDistributedOrder.ProductsPackage { return mkbImpl() }
        if let mkbImpl = mkbImpl as? () -> Any { return Mockingbird.dynamicCast(mkbImpl()) as SimpleDistributedOrder.ProductsPackage }
        for mkbTargetBox in self.mockingbirdContext.proxy.targets(for: $0) {
          switch mkbTargetBox.target {
          case .super:
            return super.`package`
          case .object(let mkbObject):
            guard var mkbObject = mkbObject as? MockingbirdSupertype else { break }
            let mkbValue: SimpleDistributedOrder.ProductsPackage = mkbObject.`package`
            self.mockingbirdContext.proxy.updateTarget(&mkbObject, in: mkbTargetBox)
            return mkbValue
          }
        }
        if let mkbValue = self.mockingbirdContext.stubbing.defaultValueProvider.value.provideValue(for: (SimpleDistributedOrder.ProductsPackage).self) { return mkbValue }
        self.mockingbirdContext.stubbing.failTest(for: $0, at: self.mockingbirdContext.sourceLocation)
      }
    }
    set {
      return self.mockingbirdContext.mocking.didInvoke(Mockingbird.SwiftInvocation(selectorName: "package.setter", setterSelectorName: "package.setter", selectorType: Mockingbird.SelectorType.setter, arguments: [Mockingbird.ArgumentMatcher(newValue)], returnType: Swift.ObjectIdentifier(Void.self))) {
        self.mockingbirdContext.recordInvocation($0)
        let mkbImpl = self.mockingbirdContext.stubbing.implementation(for: $0)
        if let mkbImpl = mkbImpl as? (SimpleDistributedOrder.ProductsPackage) -> Void { return mkbImpl(newValue) }
        if let mkbImpl = mkbImpl as? () -> Void { return mkbImpl() }
        if let mkbImpl = mkbImpl as? (Any?) -> Any { return Mockingbird.dynamicCast(mkbImpl(newValue as Any?)) as Void }
        if let mkbImpl = mkbImpl as? () -> Any { return Mockingbird.dynamicCast(mkbImpl()) as Void }
        for mkbTargetBox in self.mockingbirdContext.proxy.targets(for: $0) {
          switch mkbTargetBox.target {
          case .super:
            return super.`package` = newValue
          case .object(let mkbObject):
            guard var mkbObject = mkbObject as? MockingbirdSupertype else { break }
            let mkbValue: Void = mkbObject.`package` = newValue
            self.mockingbirdContext.proxy.updateTarget(&mkbObject, in: mkbTargetBox)
            return mkbValue
          }
        }
        if let mkbValue = self.mockingbirdContext.stubbing.defaultValueProvider.value.provideValue(for: (Void).self) { return mkbValue }
        self.mockingbirdContext.stubbing.failTest(for: $0, at: self.mockingbirdContext.sourceLocation)
      }
    }
  }

  public func getPackage() -> Mockingbird.Mockable<Mockingbird.PropertyGetterDeclaration, () -> SimpleDistributedOrder.ProductsPackage, SimpleDistributedOrder.ProductsPackage> {
    return Mockingbird.Mockable<Mockingbird.PropertyGetterDeclaration, () -> SimpleDistributedOrder.ProductsPackage, SimpleDistributedOrder.ProductsPackage>(context: self.mockingbirdContext, invocation: Mockingbird.SwiftInvocation(selectorName: "package.getter", setterSelectorName: "package.setter", selectorType: Mockingbird.SelectorType.getter, arguments: [], returnType: Swift.ObjectIdentifier((SimpleDistributedOrder.ProductsPackage).self)))
  }

  public func setPackage(_ newValue: @autoclosure () -> SimpleDistributedOrder.ProductsPackage) -> Mockingbird.Mockable<Mockingbird.PropertySetterDeclaration, (SimpleDistributedOrder.ProductsPackage) -> Void, Void> {
    return Mockingbird.Mockable<Mockingbird.PropertySetterDeclaration, (SimpleDistributedOrder.ProductsPackage) -> Void, Void>(context: self.mockingbirdContext, invocation: Mockingbird.SwiftInvocation(selectorName: "package.setter", setterSelectorName: "package.setter", selectorType: Mockingbird.SelectorType.setter, arguments: [Mockingbird.resolve(newValue)], returnType: Swift.ObjectIdentifier(Void.self)))
  }

  // MARK: Mocked `getItemNames`()
  public override func `getItemNames`() -> String {
    return self.mockingbirdContext.mocking.didInvoke(Mockingbird.SwiftInvocation(selectorName: "`getItemNames`() -> String", selectorType: Mockingbird.SelectorType.method, arguments: [], returnType: Swift.ObjectIdentifier((String).self))) {
      self.mockingbirdContext.recordInvocation($0)
      let mkbImpl = self.mockingbirdContext.stubbing.implementation(for: $0)
      if let mkbImpl = mkbImpl as? () -> String { return mkbImpl() }
      for mkbTargetBox in self.mockingbirdContext.proxy.targets(for: $0) {
        switch mkbTargetBox.target {
        case .super:
          return super.`getItemNames`()
        case .object(let mkbObject):
          guard var mkbObject = mkbObject as? MockingbirdSupertype else { break }
          let mkbValue: String = mkbObject.`getItemNames`()
          self.mockingbirdContext.proxy.updateTarget(&mkbObject, in: mkbTargetBox)
          return mkbValue
        }
      }
      if let mkbValue = self.mockingbirdContext.stubbing.defaultValueProvider.value.provideValue(for: (String).self) { return mkbValue }
      self.mockingbirdContext.stubbing.failTest(for: $0, at: self.mockingbirdContext.sourceLocation)
    }
  }

  public func `getItemNames`() -> Mockingbird.Mockable<Mockingbird.FunctionDeclaration, () -> String, String> {
    return Mockingbird.Mockable<Mockingbird.FunctionDeclaration, () -> String, String>(context: self.mockingbirdContext, invocation: Mockingbird.SwiftInvocation(selectorName: "`getItemNames`() -> String", selectorType: Mockingbird.SelectorType.method, arguments: [], returnType: Swift.ObjectIdentifier((String).self)))
  }

  // MARK: Mocked init(`package`: SimpleDistributedOrder.ProductsPackage)
  public required override init(`package`: SimpleDistributedOrder.ProductsPackage) {
    super.init(package: `package`)
    self.mockingbirdContext.mocking.didInvoke(Mockingbird.SwiftInvocation(selectorName: "init(`package`: SimpleDistributedOrder.ProductsPackage)", selectorType: Mockingbird.SelectorType.method, arguments: [Mockingbird.ArgumentMatcher(`package`)], returnType: Swift.ObjectIdentifier((Void).self)))
  }

  public func initialize(`package`: @autoclosure () -> SimpleDistributedOrder.ProductsPackage) -> Mockingbird.Mockable<Mockingbird.FunctionDeclaration, (SimpleDistributedOrder.ProductsPackage) -> Void, Void> {
    return Mockingbird.Mockable<Mockingbird.FunctionDeclaration, (SimpleDistributedOrder.ProductsPackage) -> Void, Void>(context: self.mockingbirdContext, invocation: Mockingbird.SwiftInvocation(selectorName: "init(`package`: SimpleDistributedOrder.ProductsPackage)", selectorType: Mockingbird.SelectorType.method, arguments: [Mockingbird.resolve(`package`)], returnType: Swift.ObjectIdentifier((Void).self)))
  }
}

/// Returns an abstract mock which should be initialized using `mock(ProductPackageViewModel.self).initialize(…)`.
public func mock(_ type: SimpleDistributedOrder.ProductPackageViewModel.Type, file: StaticString = #file, line: UInt = #line) -> ProductPackageViewModelMock.InitializerProxy.Type {
  return ProductPackageViewModelMock.InitializerProxy.self
}

// MARK: - Mocked ProductSwiftDataServiceProtocol
public final class ProductSwiftDataServiceProtocolMock: SimpleDistributedOrder.ProductSwiftDataServiceProtocol, Mockingbird.Mock {
  typealias MockingbirdSupertype = SimpleDistributedOrder.ProductSwiftDataServiceProtocol
  public static let mockingbirdContext = Mockingbird.Context()
  public let mockingbirdContext = Mockingbird.Context(["generator_version": "0.20.0", "module_name": "SimpleDistributedOrder"])

  fileprivate init(sourceLocation: Mockingbird.SourceLocation) {
    self.mockingbirdContext.sourceLocation = sourceLocation
    ProductSwiftDataServiceProtocolMock.mockingbirdContext.sourceLocation = sourceLocation
  }

  // MARK: Mocked `getModelContainer`()
  public func `getModelContainer`() -> ModelContainer {
    return self.mockingbirdContext.mocking.didInvoke(Mockingbird.SwiftInvocation(selectorName: "`getModelContainer`() -> ModelContainer", selectorType: Mockingbird.SelectorType.method, arguments: [], returnType: Swift.ObjectIdentifier((ModelContainer).self))) {
      self.mockingbirdContext.recordInvocation($0)
      let mkbImpl = self.mockingbirdContext.stubbing.implementation(for: $0)
      if let mkbImpl = mkbImpl as? () -> ModelContainer { return mkbImpl() }
      for mkbTargetBox in self.mockingbirdContext.proxy.targets(for: $0) {
        switch mkbTargetBox.target {
        case .super:
          break
        case .object(let mkbObject):
          guard var mkbObject = mkbObject as? MockingbirdSupertype else { break }
          let mkbValue: ModelContainer = mkbObject.`getModelContainer`()
          self.mockingbirdContext.proxy.updateTarget(&mkbObject, in: mkbTargetBox)
          return mkbValue
        }
      }
      if let mkbValue = self.mockingbirdContext.stubbing.defaultValueProvider.value.provideValue(for: (ModelContainer).self) { return mkbValue }
      self.mockingbirdContext.stubbing.failTest(for: $0, at: self.mockingbirdContext.sourceLocation)
    }
  }

  public func `getModelContainer`() -> Mockingbird.Mockable<Mockingbird.FunctionDeclaration, () -> ModelContainer, ModelContainer> {
    return Mockingbird.Mockable<Mockingbird.FunctionDeclaration, () -> ModelContainer, ModelContainer>(context: self.mockingbirdContext, invocation: Mockingbird.SwiftInvocation(selectorName: "`getModelContainer`() -> ModelContainer", selectorType: Mockingbird.SelectorType.method, arguments: [], returnType: Swift.ObjectIdentifier((ModelContainer).self)))
  }

  // MARK: Mocked `fetchProductList`()
  public func `fetchProductList`() -> [SimpleDistributedOrder.ProductItem] {
    return self.mockingbirdContext.mocking.didInvoke(Mockingbird.SwiftInvocation(selectorName: "`fetchProductList`() -> [SimpleDistributedOrder.ProductItem]", selectorType: Mockingbird.SelectorType.method, arguments: [], returnType: Swift.ObjectIdentifier(([SimpleDistributedOrder.ProductItem]).self))) {
      self.mockingbirdContext.recordInvocation($0)
      let mkbImpl = self.mockingbirdContext.stubbing.implementation(for: $0)
      if let mkbImpl = mkbImpl as? () -> [SimpleDistributedOrder.ProductItem] { return mkbImpl() }
      for mkbTargetBox in self.mockingbirdContext.proxy.targets(for: $0) {
        switch mkbTargetBox.target {
        case .super:
          break
        case .object(let mkbObject):
          guard var mkbObject = mkbObject as? MockingbirdSupertype else { break }
          let mkbValue: [SimpleDistributedOrder.ProductItem] = mkbObject.`fetchProductList`()
          self.mockingbirdContext.proxy.updateTarget(&mkbObject, in: mkbTargetBox)
          return mkbValue
        }
      }
      if let mkbValue = self.mockingbirdContext.stubbing.defaultValueProvider.value.provideValue(for: ([SimpleDistributedOrder.ProductItem]).self) { return mkbValue }
      self.mockingbirdContext.stubbing.failTest(for: $0, at: self.mockingbirdContext.sourceLocation)
    }
  }

  public func `fetchProductList`() -> Mockingbird.Mockable<Mockingbird.FunctionDeclaration, () -> [SimpleDistributedOrder.ProductItem], [SimpleDistributedOrder.ProductItem]> {
    return Mockingbird.Mockable<Mockingbird.FunctionDeclaration, () -> [SimpleDistributedOrder.ProductItem], [SimpleDistributedOrder.ProductItem]>(context: self.mockingbirdContext, invocation: Mockingbird.SwiftInvocation(selectorName: "`fetchProductList`() -> [SimpleDistributedOrder.ProductItem]", selectorType: Mockingbird.SelectorType.method, arguments: [], returnType: Swift.ObjectIdentifier(([SimpleDistributedOrder.ProductItem]).self)))
  }
}

/// Returns a concrete mock of `ProductSwiftDataServiceProtocol`.
public func mock(_ type: SimpleDistributedOrder.ProductSwiftDataServiceProtocol.Protocol, file: StaticString = #file, line: UInt = #line) -> ProductSwiftDataServiceProtocolMock {
  return ProductSwiftDataServiceProtocolMock(sourceLocation: Mockingbird.SourceLocation(file, line))
}

// MARK: - Mocked ProductSwiftDataService
public final class ProductSwiftDataServiceMock: Mockingbird.Mock {
  typealias MockingbirdSupertype = SimpleDistributedOrder.ProductSwiftDataService
  public static let mockingbirdContext = Mockingbird.Context()
  public let mockingbirdContext = Mockingbird.Context(["generator_version": "0.20.0", "module_name": "SimpleDistributedOrder"])
}

@available(*, unavailable, message: "'ProductSwiftDataService' does not declare any accessible designated initializers and cannot be mocked")
public func mock(_ type: SimpleDistributedOrder.ProductSwiftDataService.Type, file: StaticString = #file, line: UInt = #line) -> ProductSwiftDataServiceMock {
  fatalError()
}

// MARK: - Mocked ProductsPackage
public final class ProductsPackageMock: SimpleDistributedOrder.ProductsPackage, Mockingbird.Mock {
  typealias MockingbirdSupertype = SimpleDistributedOrder.ProductsPackage
  public static let mockingbirdContext = Mockingbird.Context()
  public let mockingbirdContext = Mockingbird.Context(["generator_version": "0.20.0", "module_name": "SimpleDistributedOrder"])

  public enum InitializerProxy {
    public static func initialize(__file: StaticString = #file, __line: UInt = #line) -> ProductsPackageMock {
      let mock: ProductsPackageMock = ProductsPackageMock()
      mock.mockingbirdContext.sourceLocation = SourceLocation(__file, __line)
      return mock
    }

    public static func initialize(`name`: String, `totalPrice`: Double, `totalWeight`: Int, `courierCharge`: Double, `products`: [SimpleDistributedOrder.ProductItem], __file: StaticString = #file, __line: UInt = #line) -> ProductsPackageMock {
      let mock: ProductsPackageMock = ProductsPackageMock(name: `name`, totalPrice: `totalPrice`, totalWeight: `totalWeight`, courierCharge: `courierCharge`, products: `products`)
      mock.mockingbirdContext.sourceLocation = SourceLocation(__file, __line)
      return mock
    }
  }

  // MARK: Mocked courierCharge
  override public var `courierCharge`: Double {
    get {
      return self.mockingbirdContext.mocking.didInvoke(Mockingbird.SwiftInvocation(selectorName: "courierCharge.getter", setterSelectorName: "courierCharge.setter", selectorType: Mockingbird.SelectorType.getter, arguments: [], returnType: Swift.ObjectIdentifier((Double).self))) {
        self.mockingbirdContext.recordInvocation($0)
        let mkbImpl = self.mockingbirdContext.stubbing.implementation(for: $0)
        if let mkbImpl = mkbImpl as? () -> Double { return mkbImpl() }
        if let mkbImpl = mkbImpl as? () -> Any { return Mockingbird.dynamicCast(mkbImpl()) as Double }
        for mkbTargetBox in self.mockingbirdContext.proxy.targets(for: $0) {
          switch mkbTargetBox.target {
          case .super:
            return super.`courierCharge`
          case .object(let mkbObject):
            guard var mkbObject = mkbObject as? MockingbirdSupertype else { break }
            let mkbValue: Double = mkbObject.`courierCharge`
            self.mockingbirdContext.proxy.updateTarget(&mkbObject, in: mkbTargetBox)
            return mkbValue
          }
        }
        if let mkbValue = self.mockingbirdContext.stubbing.defaultValueProvider.value.provideValue(for: (Double).self) { return mkbValue }
        self.mockingbirdContext.stubbing.failTest(for: $0, at: self.mockingbirdContext.sourceLocation)
      }
    }
    set {
      return self.mockingbirdContext.mocking.didInvoke(Mockingbird.SwiftInvocation(selectorName: "courierCharge.setter", setterSelectorName: "courierCharge.setter", selectorType: Mockingbird.SelectorType.setter, arguments: [Mockingbird.ArgumentMatcher(newValue)], returnType: Swift.ObjectIdentifier(Void.self))) {
        self.mockingbirdContext.recordInvocation($0)
        let mkbImpl = self.mockingbirdContext.stubbing.implementation(for: $0)
        if let mkbImpl = mkbImpl as? (Double) -> Void { return mkbImpl(newValue) }
        if let mkbImpl = mkbImpl as? () -> Void { return mkbImpl() }
        if let mkbImpl = mkbImpl as? (Any?) -> Any { return Mockingbird.dynamicCast(mkbImpl(newValue as Any?)) as Void }
        if let mkbImpl = mkbImpl as? () -> Any { return Mockingbird.dynamicCast(mkbImpl()) as Void }
        for mkbTargetBox in self.mockingbirdContext.proxy.targets(for: $0) {
          switch mkbTargetBox.target {
          case .super:
            return super.`courierCharge` = newValue
          case .object(let mkbObject):
            guard var mkbObject = mkbObject as? MockingbirdSupertype else { break }
            let mkbValue: Void = mkbObject.`courierCharge` = newValue
            self.mockingbirdContext.proxy.updateTarget(&mkbObject, in: mkbTargetBox)
            return mkbValue
          }
        }
        if let mkbValue = self.mockingbirdContext.stubbing.defaultValueProvider.value.provideValue(for: (Void).self) { return mkbValue }
        self.mockingbirdContext.stubbing.failTest(for: $0, at: self.mockingbirdContext.sourceLocation)
      }
    }
  }

  public func getCourierCharge() -> Mockingbird.Mockable<Mockingbird.PropertyGetterDeclaration, () -> Double, Double> {
    return Mockingbird.Mockable<Mockingbird.PropertyGetterDeclaration, () -> Double, Double>(context: self.mockingbirdContext, invocation: Mockingbird.SwiftInvocation(selectorName: "courierCharge.getter", setterSelectorName: "courierCharge.setter", selectorType: Mockingbird.SelectorType.getter, arguments: [], returnType: Swift.ObjectIdentifier((Double).self)))
  }

  public func setCourierCharge(_ newValue: @autoclosure () -> Double) -> Mockingbird.Mockable<Mockingbird.PropertySetterDeclaration, (Double) -> Void, Void> {
    return Mockingbird.Mockable<Mockingbird.PropertySetterDeclaration, (Double) -> Void, Void>(context: self.mockingbirdContext, invocation: Mockingbird.SwiftInvocation(selectorName: "courierCharge.setter", setterSelectorName: "courierCharge.setter", selectorType: Mockingbird.SelectorType.setter, arguments: [Mockingbird.resolve(newValue)], returnType: Swift.ObjectIdentifier(Void.self)))
  }

  // MARK: Mocked name
  override public var `name`: String {
    get {
      return self.mockingbirdContext.mocking.didInvoke(Mockingbird.SwiftInvocation(selectorName: "name.getter", setterSelectorName: "name.setter", selectorType: Mockingbird.SelectorType.getter, arguments: [], returnType: Swift.ObjectIdentifier((String).self))) {
        self.mockingbirdContext.recordInvocation($0)
        let mkbImpl = self.mockingbirdContext.stubbing.implementation(for: $0)
        if let mkbImpl = mkbImpl as? () -> String { return mkbImpl() }
        if let mkbImpl = mkbImpl as? () -> Any { return Mockingbird.dynamicCast(mkbImpl()) as String }
        for mkbTargetBox in self.mockingbirdContext.proxy.targets(for: $0) {
          switch mkbTargetBox.target {
          case .super:
            return super.`name`
          case .object(let mkbObject):
            guard var mkbObject = mkbObject as? MockingbirdSupertype else { break }
            let mkbValue: String = mkbObject.`name`
            self.mockingbirdContext.proxy.updateTarget(&mkbObject, in: mkbTargetBox)
            return mkbValue
          }
        }
        if let mkbValue = self.mockingbirdContext.stubbing.defaultValueProvider.value.provideValue(for: (String).self) { return mkbValue }
        self.mockingbirdContext.stubbing.failTest(for: $0, at: self.mockingbirdContext.sourceLocation)
      }
    }
    set {
      return self.mockingbirdContext.mocking.didInvoke(Mockingbird.SwiftInvocation(selectorName: "name.setter", setterSelectorName: "name.setter", selectorType: Mockingbird.SelectorType.setter, arguments: [Mockingbird.ArgumentMatcher(newValue)], returnType: Swift.ObjectIdentifier(Void.self))) {
        self.mockingbirdContext.recordInvocation($0)
        let mkbImpl = self.mockingbirdContext.stubbing.implementation(for: $0)
        if let mkbImpl = mkbImpl as? (String) -> Void { return mkbImpl(newValue) }
        if let mkbImpl = mkbImpl as? () -> Void { return mkbImpl() }
        if let mkbImpl = mkbImpl as? (Any?) -> Any { return Mockingbird.dynamicCast(mkbImpl(newValue as Any?)) as Void }
        if let mkbImpl = mkbImpl as? () -> Any { return Mockingbird.dynamicCast(mkbImpl()) as Void }
        for mkbTargetBox in self.mockingbirdContext.proxy.targets(for: $0) {
          switch mkbTargetBox.target {
          case .super:
            return super.`name` = newValue
          case .object(let mkbObject):
            guard var mkbObject = mkbObject as? MockingbirdSupertype else { break }
            let mkbValue: Void = mkbObject.`name` = newValue
            self.mockingbirdContext.proxy.updateTarget(&mkbObject, in: mkbTargetBox)
            return mkbValue
          }
        }
        if let mkbValue = self.mockingbirdContext.stubbing.defaultValueProvider.value.provideValue(for: (Void).self) { return mkbValue }
        self.mockingbirdContext.stubbing.failTest(for: $0, at: self.mockingbirdContext.sourceLocation)
      }
    }
  }

  public func getName() -> Mockingbird.Mockable<Mockingbird.PropertyGetterDeclaration, () -> String, String> {
    return Mockingbird.Mockable<Mockingbird.PropertyGetterDeclaration, () -> String, String>(context: self.mockingbirdContext, invocation: Mockingbird.SwiftInvocation(selectorName: "name.getter", setterSelectorName: "name.setter", selectorType: Mockingbird.SelectorType.getter, arguments: [], returnType: Swift.ObjectIdentifier((String).self)))
  }

  public func setName(_ newValue: @autoclosure () -> String) -> Mockingbird.Mockable<Mockingbird.PropertySetterDeclaration, (String) -> Void, Void> {
    return Mockingbird.Mockable<Mockingbird.PropertySetterDeclaration, (String) -> Void, Void>(context: self.mockingbirdContext, invocation: Mockingbird.SwiftInvocation(selectorName: "name.setter", setterSelectorName: "name.setter", selectorType: Mockingbird.SelectorType.setter, arguments: [Mockingbird.resolve(newValue)], returnType: Swift.ObjectIdentifier(Void.self)))
  }

  // MARK: Mocked products
  override public var `products`: [SimpleDistributedOrder.ProductItem] {
    get {
      return self.mockingbirdContext.mocking.didInvoke(Mockingbird.SwiftInvocation(selectorName: "products.getter", setterSelectorName: "products.setter", selectorType: Mockingbird.SelectorType.getter, arguments: [], returnType: Swift.ObjectIdentifier(([SimpleDistributedOrder.ProductItem]).self))) {
        self.mockingbirdContext.recordInvocation($0)
        let mkbImpl = self.mockingbirdContext.stubbing.implementation(for: $0)
        if let mkbImpl = mkbImpl as? () -> [SimpleDistributedOrder.ProductItem] { return mkbImpl() }
        if let mkbImpl = mkbImpl as? () -> Any { return Mockingbird.dynamicCast(mkbImpl()) as [SimpleDistributedOrder.ProductItem] }
        for mkbTargetBox in self.mockingbirdContext.proxy.targets(for: $0) {
          switch mkbTargetBox.target {
          case .super:
            return super.`products`
          case .object(let mkbObject):
            guard var mkbObject = mkbObject as? MockingbirdSupertype else { break }
            let mkbValue: [SimpleDistributedOrder.ProductItem] = mkbObject.`products`
            self.mockingbirdContext.proxy.updateTarget(&mkbObject, in: mkbTargetBox)
            return mkbValue
          }
        }
        if let mkbValue = self.mockingbirdContext.stubbing.defaultValueProvider.value.provideValue(for: ([SimpleDistributedOrder.ProductItem]).self) { return mkbValue }
        self.mockingbirdContext.stubbing.failTest(for: $0, at: self.mockingbirdContext.sourceLocation)
      }
    }
    set {
      return self.mockingbirdContext.mocking.didInvoke(Mockingbird.SwiftInvocation(selectorName: "products.setter", setterSelectorName: "products.setter", selectorType: Mockingbird.SelectorType.setter, arguments: [Mockingbird.ArgumentMatcher(newValue)], returnType: Swift.ObjectIdentifier(Void.self))) {
        self.mockingbirdContext.recordInvocation($0)
        let mkbImpl = self.mockingbirdContext.stubbing.implementation(for: $0)
        if let mkbImpl = mkbImpl as? ([SimpleDistributedOrder.ProductItem]) -> Void { return mkbImpl(newValue) }
        if let mkbImpl = mkbImpl as? () -> Void { return mkbImpl() }
        if let mkbImpl = mkbImpl as? (Any?) -> Any { return Mockingbird.dynamicCast(mkbImpl(newValue as Any?)) as Void }
        if let mkbImpl = mkbImpl as? () -> Any { return Mockingbird.dynamicCast(mkbImpl()) as Void }
        for mkbTargetBox in self.mockingbirdContext.proxy.targets(for: $0) {
          switch mkbTargetBox.target {
          case .super:
            return super.`products` = newValue
          case .object(let mkbObject):
            guard var mkbObject = mkbObject as? MockingbirdSupertype else { break }
            let mkbValue: Void = mkbObject.`products` = newValue
            self.mockingbirdContext.proxy.updateTarget(&mkbObject, in: mkbTargetBox)
            return mkbValue
          }
        }
        if let mkbValue = self.mockingbirdContext.stubbing.defaultValueProvider.value.provideValue(for: (Void).self) { return mkbValue }
        self.mockingbirdContext.stubbing.failTest(for: $0, at: self.mockingbirdContext.sourceLocation)
      }
    }
  }

  public func getProducts() -> Mockingbird.Mockable<Mockingbird.PropertyGetterDeclaration, () -> [SimpleDistributedOrder.ProductItem], [SimpleDistributedOrder.ProductItem]> {
    return Mockingbird.Mockable<Mockingbird.PropertyGetterDeclaration, () -> [SimpleDistributedOrder.ProductItem], [SimpleDistributedOrder.ProductItem]>(context: self.mockingbirdContext, invocation: Mockingbird.SwiftInvocation(selectorName: "products.getter", setterSelectorName: "products.setter", selectorType: Mockingbird.SelectorType.getter, arguments: [], returnType: Swift.ObjectIdentifier(([SimpleDistributedOrder.ProductItem]).self)))
  }

  public func setProducts(_ newValue: @autoclosure () -> [SimpleDistributedOrder.ProductItem]) -> Mockingbird.Mockable<Mockingbird.PropertySetterDeclaration, ([SimpleDistributedOrder.ProductItem]) -> Void, Void> {
    return Mockingbird.Mockable<Mockingbird.PropertySetterDeclaration, ([SimpleDistributedOrder.ProductItem]) -> Void, Void>(context: self.mockingbirdContext, invocation: Mockingbird.SwiftInvocation(selectorName: "products.setter", setterSelectorName: "products.setter", selectorType: Mockingbird.SelectorType.setter, arguments: [Mockingbird.resolve(newValue)], returnType: Swift.ObjectIdentifier(Void.self)))
  }

  // MARK: Mocked totalPrice
  override public var `totalPrice`: Double {
    get {
      return self.mockingbirdContext.mocking.didInvoke(Mockingbird.SwiftInvocation(selectorName: "totalPrice.getter", setterSelectorName: "totalPrice.setter", selectorType: Mockingbird.SelectorType.getter, arguments: [], returnType: Swift.ObjectIdentifier((Double).self))) {
        self.mockingbirdContext.recordInvocation($0)
        let mkbImpl = self.mockingbirdContext.stubbing.implementation(for: $0)
        if let mkbImpl = mkbImpl as? () -> Double { return mkbImpl() }
        if let mkbImpl = mkbImpl as? () -> Any { return Mockingbird.dynamicCast(mkbImpl()) as Double }
        for mkbTargetBox in self.mockingbirdContext.proxy.targets(for: $0) {
          switch mkbTargetBox.target {
          case .super:
            return super.`totalPrice`
          case .object(let mkbObject):
            guard var mkbObject = mkbObject as? MockingbirdSupertype else { break }
            let mkbValue: Double = mkbObject.`totalPrice`
            self.mockingbirdContext.proxy.updateTarget(&mkbObject, in: mkbTargetBox)
            return mkbValue
          }
        }
        if let mkbValue = self.mockingbirdContext.stubbing.defaultValueProvider.value.provideValue(for: (Double).self) { return mkbValue }
        self.mockingbirdContext.stubbing.failTest(for: $0, at: self.mockingbirdContext.sourceLocation)
      }
    }
    set {
      return self.mockingbirdContext.mocking.didInvoke(Mockingbird.SwiftInvocation(selectorName: "totalPrice.setter", setterSelectorName: "totalPrice.setter", selectorType: Mockingbird.SelectorType.setter, arguments: [Mockingbird.ArgumentMatcher(newValue)], returnType: Swift.ObjectIdentifier(Void.self))) {
        self.mockingbirdContext.recordInvocation($0)
        let mkbImpl = self.mockingbirdContext.stubbing.implementation(for: $0)
        if let mkbImpl = mkbImpl as? (Double) -> Void { return mkbImpl(newValue) }
        if let mkbImpl = mkbImpl as? () -> Void { return mkbImpl() }
        if let mkbImpl = mkbImpl as? (Any?) -> Any { return Mockingbird.dynamicCast(mkbImpl(newValue as Any?)) as Void }
        if let mkbImpl = mkbImpl as? () -> Any { return Mockingbird.dynamicCast(mkbImpl()) as Void }
        for mkbTargetBox in self.mockingbirdContext.proxy.targets(for: $0) {
          switch mkbTargetBox.target {
          case .super:
            return super.`totalPrice` = newValue
          case .object(let mkbObject):
            guard var mkbObject = mkbObject as? MockingbirdSupertype else { break }
            let mkbValue: Void = mkbObject.`totalPrice` = newValue
            self.mockingbirdContext.proxy.updateTarget(&mkbObject, in: mkbTargetBox)
            return mkbValue
          }
        }
        if let mkbValue = self.mockingbirdContext.stubbing.defaultValueProvider.value.provideValue(for: (Void).self) { return mkbValue }
        self.mockingbirdContext.stubbing.failTest(for: $0, at: self.mockingbirdContext.sourceLocation)
      }
    }
  }

  public func getTotalPrice() -> Mockingbird.Mockable<Mockingbird.PropertyGetterDeclaration, () -> Double, Double> {
    return Mockingbird.Mockable<Mockingbird.PropertyGetterDeclaration, () -> Double, Double>(context: self.mockingbirdContext, invocation: Mockingbird.SwiftInvocation(selectorName: "totalPrice.getter", setterSelectorName: "totalPrice.setter", selectorType: Mockingbird.SelectorType.getter, arguments: [], returnType: Swift.ObjectIdentifier((Double).self)))
  }

  public func setTotalPrice(_ newValue: @autoclosure () -> Double) -> Mockingbird.Mockable<Mockingbird.PropertySetterDeclaration, (Double) -> Void, Void> {
    return Mockingbird.Mockable<Mockingbird.PropertySetterDeclaration, (Double) -> Void, Void>(context: self.mockingbirdContext, invocation: Mockingbird.SwiftInvocation(selectorName: "totalPrice.setter", setterSelectorName: "totalPrice.setter", selectorType: Mockingbird.SelectorType.setter, arguments: [Mockingbird.resolve(newValue)], returnType: Swift.ObjectIdentifier(Void.self)))
  }

  // MARK: Mocked totalWeight
  override public var `totalWeight`: Int {
    get {
      return self.mockingbirdContext.mocking.didInvoke(Mockingbird.SwiftInvocation(selectorName: "totalWeight.getter", setterSelectorName: "totalWeight.setter", selectorType: Mockingbird.SelectorType.getter, arguments: [], returnType: Swift.ObjectIdentifier((Int).self))) {
        self.mockingbirdContext.recordInvocation($0)
        let mkbImpl = self.mockingbirdContext.stubbing.implementation(for: $0)
        if let mkbImpl = mkbImpl as? () -> Int { return mkbImpl() }
        if let mkbImpl = mkbImpl as? () -> Any { return Mockingbird.dynamicCast(mkbImpl()) as Int }
        for mkbTargetBox in self.mockingbirdContext.proxy.targets(for: $0) {
          switch mkbTargetBox.target {
          case .super:
            return super.`totalWeight`
          case .object(let mkbObject):
            guard var mkbObject = mkbObject as? MockingbirdSupertype else { break }
            let mkbValue: Int = mkbObject.`totalWeight`
            self.mockingbirdContext.proxy.updateTarget(&mkbObject, in: mkbTargetBox)
            return mkbValue
          }
        }
        if let mkbValue = self.mockingbirdContext.stubbing.defaultValueProvider.value.provideValue(for: (Int).self) { return mkbValue }
        self.mockingbirdContext.stubbing.failTest(for: $0, at: self.mockingbirdContext.sourceLocation)
      }
    }
    set {
      return self.mockingbirdContext.mocking.didInvoke(Mockingbird.SwiftInvocation(selectorName: "totalWeight.setter", setterSelectorName: "totalWeight.setter", selectorType: Mockingbird.SelectorType.setter, arguments: [Mockingbird.ArgumentMatcher(newValue)], returnType: Swift.ObjectIdentifier(Void.self))) {
        self.mockingbirdContext.recordInvocation($0)
        let mkbImpl = self.mockingbirdContext.stubbing.implementation(for: $0)
        if let mkbImpl = mkbImpl as? (Int) -> Void { return mkbImpl(newValue) }
        if let mkbImpl = mkbImpl as? () -> Void { return mkbImpl() }
        if let mkbImpl = mkbImpl as? (Any?) -> Any { return Mockingbird.dynamicCast(mkbImpl(newValue as Any?)) as Void }
        if let mkbImpl = mkbImpl as? () -> Any { return Mockingbird.dynamicCast(mkbImpl()) as Void }
        for mkbTargetBox in self.mockingbirdContext.proxy.targets(for: $0) {
          switch mkbTargetBox.target {
          case .super:
            return super.`totalWeight` = newValue
          case .object(let mkbObject):
            guard var mkbObject = mkbObject as? MockingbirdSupertype else { break }
            let mkbValue: Void = mkbObject.`totalWeight` = newValue
            self.mockingbirdContext.proxy.updateTarget(&mkbObject, in: mkbTargetBox)
            return mkbValue
          }
        }
        if let mkbValue = self.mockingbirdContext.stubbing.defaultValueProvider.value.provideValue(for: (Void).self) { return mkbValue }
        self.mockingbirdContext.stubbing.failTest(for: $0, at: self.mockingbirdContext.sourceLocation)
      }
    }
  }

  public func getTotalWeight() -> Mockingbird.Mockable<Mockingbird.PropertyGetterDeclaration, () -> Int, Int> {
    return Mockingbird.Mockable<Mockingbird.PropertyGetterDeclaration, () -> Int, Int>(context: self.mockingbirdContext, invocation: Mockingbird.SwiftInvocation(selectorName: "totalWeight.getter", setterSelectorName: "totalWeight.setter", selectorType: Mockingbird.SelectorType.getter, arguments: [], returnType: Swift.ObjectIdentifier((Int).self)))
  }

  public func setTotalWeight(_ newValue: @autoclosure () -> Int) -> Mockingbird.Mockable<Mockingbird.PropertySetterDeclaration, (Int) -> Void, Void> {
    return Mockingbird.Mockable<Mockingbird.PropertySetterDeclaration, (Int) -> Void, Void>(context: self.mockingbirdContext, invocation: Mockingbird.SwiftInvocation(selectorName: "totalWeight.setter", setterSelectorName: "totalWeight.setter", selectorType: Mockingbird.SelectorType.setter, arguments: [Mockingbird.resolve(newValue)], returnType: Swift.ObjectIdentifier(Void.self)))
  }

  // MARK: Mocked init()
  public required override init() {
    super.init()
    self.mockingbirdContext.mocking.didInvoke(Mockingbird.SwiftInvocation(selectorName: "init()", selectorType: Mockingbird.SelectorType.method, arguments: [], returnType: Swift.ObjectIdentifier((Void).self)))
  }

  public func initialize() -> Mockingbird.Mockable<Mockingbird.FunctionDeclaration, () -> Void, Void> {
    return Mockingbird.Mockable<Mockingbird.FunctionDeclaration, () -> Void, Void>(context: self.mockingbirdContext, invocation: Mockingbird.SwiftInvocation(selectorName: "init()", selectorType: Mockingbird.SelectorType.method, arguments: [], returnType: Swift.ObjectIdentifier((Void).self)))
  }

  // MARK: Mocked init(`name`: String, `totalPrice`: Double, `totalWeight`: Int, `courierCharge`: Double, `products`: [SimpleDistributedOrder.ProductItem])
  public required override init(`name`: String, `totalPrice`: Double, `totalWeight`: Int, `courierCharge`: Double, `products`: [SimpleDistributedOrder.ProductItem]) {
    super.init(name: `name`, totalPrice: `totalPrice`, totalWeight: `totalWeight`, courierCharge: `courierCharge`, products: `products`)
    self.mockingbirdContext.mocking.didInvoke(Mockingbird.SwiftInvocation(selectorName: "init(`name`: String, `totalPrice`: Double, `totalWeight`: Int, `courierCharge`: Double, `products`: [SimpleDistributedOrder.ProductItem])", selectorType: Mockingbird.SelectorType.method, arguments: [Mockingbird.ArgumentMatcher(`name`), Mockingbird.ArgumentMatcher(`totalPrice`), Mockingbird.ArgumentMatcher(`totalWeight`), Mockingbird.ArgumentMatcher(`courierCharge`), Mockingbird.ArgumentMatcher(`products`)], returnType: Swift.ObjectIdentifier((Void).self)))
  }

  public func initialize(`name`: @autoclosure () -> String, `totalPrice`: @autoclosure () -> Double, `totalWeight`: @autoclosure () -> Int, `courierCharge`: @autoclosure () -> Double, `products`: @autoclosure () -> [SimpleDistributedOrder.ProductItem]) -> Mockingbird.Mockable<Mockingbird.FunctionDeclaration, (String, Double, Int, Double, [SimpleDistributedOrder.ProductItem]) -> Void, Void> {
    return Mockingbird.Mockable<Mockingbird.FunctionDeclaration, (String, Double, Int, Double, [SimpleDistributedOrder.ProductItem]) -> Void, Void>(context: self.mockingbirdContext, invocation: Mockingbird.SwiftInvocation(selectorName: "init(`name`: String, `totalPrice`: Double, `totalWeight`: Int, `courierCharge`: Double, `products`: [SimpleDistributedOrder.ProductItem])", selectorType: Mockingbird.SelectorType.method, arguments: [Mockingbird.resolve(`name`), Mockingbird.resolve(`totalPrice`), Mockingbird.resolve(`totalWeight`), Mockingbird.resolve(`courierCharge`), Mockingbird.resolve(`products`)], returnType: Swift.ObjectIdentifier((Void).self)))
  }
}

/// Returns an abstract mock which should be initialized using `mock(ProductsPackage.self).initialize(…)`.
public func mock(_ type: SimpleDistributedOrder.ProductsPackage.Type, file: StaticString = #file, line: UInt = #line) -> ProductsPackageMock.InitializerProxy.Type {
  return ProductsPackageMock.InitializerProxy.self
}
